# Generated by Django 4.1.7 on 2023-03-16 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 12, 23, 46, 804466, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
